version: "3"
services:  
  postgres:
    container_name: postgresql
    image: postgres:9.6
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "plate"
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: fenglc/pgadmin4
    links:
      - postgres:postgres
    ports:
      - "5050:5050"
volumes:
  data:
